# Generated by Django 4.0.2 on 2022-02-20 21:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('message_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
