# Generated by Django 4.0.2 on 2022-02-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
    ]
