# Generated by Django 4.0.2 on 2022-02-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatthread_second_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatThreadManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
