# Generated by Django 4.0.2 on 2022-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/image/'),
        ),
    ]
