# Generated by Django 4.0.2 on 2022-02-15 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowerSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('date_followed', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
