// AUTH DISPATCH STATES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const AUTHENTICATED_SUCCESS='AUTHENTICATED_SUCCESS'
export const AUTHENTICATED_FAIL= 'AUTHENTICATED_FAIL'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL'
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS'

//PROFILE DISPATCH STATES
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS'
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL'